VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ]
    vb.customize [ "modifyvm", :id, "--uart1", "0x3F8", "4" ]
    vb.customize [ "modifyvm", :id, "--cableconnected1", "on" ]
  end
  config.vm.box = "ubuntu/focal64"
  config.vm.define :db do |db_config|
    db_config.vm.network :private_network, :ip => "192.168.33.10"
  end
  config.vm.define :web do |web_config|
    web_config.vm.network :private_network, :ip => "192.168.33.12"
  end
end